import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import StoreProvider from "../StoreProvider";
import { Header } from "@/components/sheard/Header";
import Footer from "@/components/sheard/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <StoreProvider>
          <Header />
          <div className="mt-[56px] px-5 md:px-5 lg:px-0 manage_layout_margin">{children}</div>
          <Footer/>
        </StoreProvider>
      </body>
    </html>
  );
}
